title = 'Mehmet Kutay Bozkurt'
baseURL = 'https://mkutay.dev'
languageCode = 'en-uk'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
copyright = 'Creative Commons Attribution-NonCommercial 4.0 for content, Unlicense for code.'
rssLimit = 10

[params]
  Author = 'Mehmet Kutay Bozkurt'
  AuthorEmail = 'hello@mkutay.dev'
  SiteDescription = "I'm Mehmet Kutay Bozkurt, a human."

[markup]
  [markup.highlight]
    style = 'rrt'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
